//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeForHomeless.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerCenter
    {
        public int VolunteerCenter_Id { get; set; }
        public string Country { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Suburb { get; set; }
        public Nullable<int> Postcode { get; set; }
        public string State { get; set; }
        public string Business_Category { get; set; }
        public string LGA { get; set; }
        public string Region { get; set; }
    }
}
